Support Hardlinks (Any number)
markusressel/zfs-inplace-rebalancing pull request #48
Opened 2024-11-06 21:15 UTC by undaunt

I took some inspiration from https://github.com/markusressel/zfs-inplace-rebalancing/issues/42 to work on a way to support any number of hardlinks.

The general workflow is all of the files in a given dataset target will be listed, inodes calculated, then files per inode grouped, such that the hardlinks will be deleted when the original file is deleted during the delete/move process, and they are then immediately recreated based off the copy. This happens per inode group so there would be no downtime of a given file.

I also added a debug mode to export a lot more output on the move/copy/hardlink process.

I removed the skip hardlink function since hardlinks are now natively supported. The read me has also been updated to reflect all of this.

The output for a given line when it is skipped will reflect whether a given file is or is not part of a hardlink inode group.

2024-11-09 00:01 UTC, markusressel requested changes
Thx for the PR!

I have left some comments to further improve it :nerd_face: 

Also: Tests seem to be failing, so we need to fix them.

2024-11-09 00:01 UTC, markusressel commented on zfs-inplace-rebalancing.sh
> +    line_nr=$(grep -xF -n -e "${file_path}" "./${rebalance_db_file_name}" | head -n 1 | cut -d: -f1)
Same thing, why add `-e` here?

2025-01-09 21:49 UTC, undaunt commented
I'm going to try and take a look in the near future, super busy recently with kids / holidays / etc. and Q4 at work.

2025-02-03 20:58 UTC, loganjohnlong commented
Any updates on this? I would love to be able to run this with hardlinks

2025-03-22 03:42 UTC, ColinHebert commented on zfs-inplace-rebalancing.sh
> -            copy_md5="${copy_md5} $(ls -lha "${tmp_file_path}" | awk '{print $1 " " $3 " " $4}')"
@undaunt any details as to why this logic had to be removed? Did it prevent the script from working with HardLinks?

2025-03-22 05:28 UTC, ColinHebert commented on zfs-inplace-rebalancing.sh
> +            echo "${cmd[@]}"
The problem with `set -x` is that you now need to `set +x` right after (if the flag is enabled) which adds more logic and code. Given that only two commands are printed this way I'd advise to not do `set -x`

2025-03-22 05:36 UTC, ColinHebert commented on zfs-inplace-rebalancing.sh
> -            copy_md5="${copy_md5} $(ls -lha "${tmp_file_path}" | awk '{print $1 " " $3 " " $4}')"
This is actually easier to do now that we moved away from md5

2025-04-15 19:13 UTC, markusressel commented
Closing this as #70 was merged.
Thx for contributing :)

2025-04-15 19:13 UTC, closed without merging